export enum CategoryTypes {
  ELECTRONICS = 'ELECTRONICS',
  HOME_AND_OFFICE = 'HOME AND OFFICE',
  HEALTH_AND_BEAUTY = 'HEALTH ANDBEAUTY',
  PHONES_AND_TABLETS = 'PHONES AND TABLETS',
  BABY_PRODUCTS= 'BABY PRODUCTS',
  COMPUTING = 'COMPUTING',
  STATIONARIES = 'STATIONARIES',
  GAMING ='GAMING',
  FITNESS_AND_SPORTS = 'FITNESS AND SPORTS',
  OTHER_CATEGORIES = 'OTHER CATEGORIES'
}
